name: marvel
description: A Marvel Studios API App.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  http: ^0.12.0 # "0.11.3+17"
  rxdart: "0.19.0" # ^0.18.1
  meta: "1.1.6"

  # json_annotation: any # ^0.2.4

  # built_value: "5.5.5"
  # built_collection: "3.1.3" # '>=2.0.0 <4.0.0'

  built_collection: ">=2.0.0 <5.0.0"
  built_value: ">=5.5.5 <7.0.0"

  flutter_image: "1.0.0"
  flutter_spinkit: "2.0.1"
  # flutter_search_bar: ^2.0.5

  random_pk: "0.0.3"

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter

  build_runner: ^1.0.0 # "0.9.2"
  # json_serializable: any # ^0.5.0

  built_value_generator: ^6.1.5 # "6.1.0"

  # analyzer: "0.32.4"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-001.png

  fonts:
    - family: Marvel
      fonts:
        - asset: assets/fonts/Marvel-Regular.ttf
        - asset: assets/fonts/Marvel-Bold.ttf
        - asset: assets/fonts/Marvel-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Marvel-Italic.ttf
          style: italic
